using ProRental.Domain.Entities;
using ProRental.Interfaces.Data;
using ProRental.Interfaces.Domain;

namespace ProRental.Domain.Controls;

public class DamageReportControl : iDamageReportCRUD, iDamageReportQuery
{
    private readonly IDamageReportMapper _damageReportMapper;

    public DamageReportControl(IDamageReportMapper damageReportMapper)
    {
        _damageReportMapper = damageReportMapper ?? throw new ArgumentNullException(nameof(damageReportMapper));
    }

    // -- iDamageReportCRUD ------------------------------------------------

    public bool SubmitDamageReport(int returnItemId, Damagereport damageReport)
    {
        if (!ValidateDamageReport(damageReport)) return false;

        try
        {
            var existing = _damageReportMapper.FindByReturnItemId(returnItemId);
            if (existing is null)
            {
                _damageReportMapper.Insert(damageReport);
            }
            else
            {
                existing.SetDescription(damageReport.GetDescription() ?? string.Empty);
                existing.SetSeverity(damageReport.GetSeverity() ?? string.Empty);
                existing.SetRepairCost(damageReport.GetRepairCost());
                existing.SetImages(damageReport.GetImages() ?? string.Empty);
                existing.SetReportDate(damageReport.GetReportDate());
                _damageReportMapper.Update(existing);
            }
            return true;
        }
        catch { return false; }
    }

    // -- Control-level method (from diagram) ------------------------------

    public bool SaveDamageReport(int returnItemId, Damagereport damageReport)
        => SubmitDamageReport(returnItemId, damageReport);

    // -- iDamageReportQuery -----------------------------------------------

    public Damagereport? GetDamageReportByReturnItem(int returnItemId)
    {
        return _damageReportMapper.FindByReturnItemId(returnItemId);
    }

    public List<Damagereport> GetDamageReportsByReturnRequest(int returnRequestId)
    {
        var all = _damageReportMapper.FindAll();
        if (all is null) return new List<Damagereport>();
        return all.ToList();
    }

    public byte[] DownloadDamageReport(int damageReportId)
    {
        var report = _damageReportMapper.FindById(damageReportId);
        if (report is null) return Array.Empty<byte>();

        var html = $@"<!DOCTYPE html>
<html><head><meta charset='utf-8'/>
<style>
  body {{ font-family: Arial, sans-serif; margin: 60px; font-size: 13px; }}
  h1   {{ color: #c0392b; font-size: 20px; margin-bottom: 4px; }}
  .subtitle {{ color: #888; font-size: 11px; margin-bottom: 24px; }}
  hr   {{ border: none; border-top: 1px solid #ddd; margin: 16px 0; }}
  .row {{ display: flex; margin-bottom: 10px; }}
  .label {{ font-weight: bold; color: #555; width: 160px; flex-shrink: 0; }}
  .badge {{ display: inline-block; padding: 2px 10px; border-radius: 12px;
            background: #c0392b; color: white; font-size: 11px; }}
  .footer {{ color: #aaa; font-size: 10px; margin-top: 40px; }}
</style></head><body>
<h1>&#9888; Damage Report</h1>
<div class='subtitle'>Return Item #{report.GetReturnItemId()} &nbsp;|&nbsp; Report #{damageReportId}</div>
<hr/>
<div class='row'><span class='label'>Description:</span><span>{System.Net.WebUtility.HtmlEncode(report.GetDescription() ?? "—")}</span></div>
<div class='row'><span class='label'>Severity:</span><span class='badge'>{System.Net.WebUtility.HtmlEncode(report.GetSeverity() ?? "—")}</span></div>
<div class='row'><span class='label'>Estimated Repair Cost:</span><span><strong>${report.GetRepairCost()?.ToString("F2") ?? "0.00"}</strong></span></div>
<div class='row'><span class='label'>Images:</span><span>{System.Net.WebUtility.HtmlEncode(report.GetImages() ?? "—")}</span></div>
<div class='row'><span class='label'>Date Reported:</span><span>{report.GetReportDate():dd MMM yyyy HH:mm} (UTC)</span></div>
<hr/>
<div class='footer'>Generated by Pro Rentals Return Processing System</div>
</body></html>";

        return System.Text.Encoding.UTF8.GetBytes(html);
    }

    // -- Control-level methods (from diagram) -----------------------------

    public bool ValidateDamageReport(Damagereport damageReport)
    {
        if (damageReport is null) return false;
        if (string.IsNullOrWhiteSpace(damageReport.GetDescription())) return false;
        if (string.IsNullOrWhiteSpace(damageReport.GetSeverity())) return false;
        if (damageReport.GetRepairCost() is null || damageReport.GetRepairCost() < 0) return false;
        if (damageReport.GetReturnItemId() <= 0) return false;
        return true;
    }
}